# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSC690 Finalproject photoNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSC690 Finalproject photoNote

  target 'CSC690 Finalproject photoNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSC690 Finalproject photoNoteUITests' do
    # Pods for testing
  end

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

end
